name: Go Test

# いつ実行するか（mainブランチにpushされた時）
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    # 実行するOS（GitHubが用意してくれるLinux）
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "lejgihes"
          MYSQL_DATABASE: "test_db"
          MYSQL_USER: "rainbow777"
          MYSQL_PASSWORD: "klehorha"
        ports:
          - 3306:3306
        # MySQLが完全に起動するまで待つための設定
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. あなたのコードをチェックアウト（ダウンロード）
      - uses: actions/checkout@v4

      # 2. Goの環境をセットアップ（バージョンは今の開発環境に合わせる）
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true # go.modのキャッシュを有効にして爆速にする

      # 3. 依存ライブラリのダウンロード
      - name: Install dependencies
        run: go mod download

      # 4. テストの実行！
      - name: Run Tests
        env:
          # DB接続用の変数（envconfig内の名前に合わせる必要があります）
          DB_USER: "rainbow777"
          DB_PASS: "klehorha"
          DATABASE: "tododb"
          DBHOST: "db"
          TESTDB: "test_db"
          TESTDBHOST: "127.0.0.1"

          GOOGLECLIENTID: "727698954425-acn415cdngffpu2rmraf687kci1nav0s.apps.googleusercontent.com"
        run: go test -v ./controllers/... ./services/... ./repository/...
